#---------------------------------------------------------------------
# GitHub Action Workflow to Deploy Flask App to AWS ElasticBeanstalk
#
# Version      Date        Info
# 1.0          2019        Initial Version
#
# Made by Luciano Santos
#---------------------------------------------------------------------

name: CI-CD Pipelines
env:
  EB_PACKAGE_S3_BUCKET_NAME : "elasticbeanstalk-sa-east-1-710542179278"
  EB_APPLICATION_NAME       : "DashAgil"
  EB_ENVIRONMENT_NAME       : "Dashagil-env"
  DEPLOY_PACKAGE_NAME       : "aws-dashagil-app-${{ github.sha }}.zip"
  AWS_REGION_NAME           : "sa-east-1"
  
  AWS_KEY_ID                : "AKIA2K345HPHLCQRQI7X"
  AWS_SECRET_KEY            : "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"


on:
  push:
    branches:
      - dev
      - hml
      - release
      - main
  pull_request:
    branches:
      - dev
      - hml
      - release
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
          
      - name: Install dependencies
        run: dotnet restore
        working-directory: src/DashAgil/DashAgil.Api

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: src/DashAgil/DashAgil.Api

      - name: Test
        run: dotnet test --no-restore --verbosity normal
        working-directory: src/DashAgil/DashAgil.Api

      - name: Publish
        run: dotnet publish -c Release -o '${{ github.workspace }}/out'
        working-directory: src/DashAgil/DashAgil.Api

      - name: Zip Package
        run: |
          cd ${{ github.workspace }}/out 
          zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./  -x  *.git*

      - name: Copy our Deployment package to S3 bucket
        run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME}}/
         
      - name: Print nice message on completion of CI Pipeline
        run : echo "CI Pipeline part finished successfully"


      - name: Configure my AWS Credentils
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id    : ${{ env.AWS_KEY_ID }}
         aws-secret-access-key: ${{ env.AWS_SECRET_KEY }}
         aws-region           : ${{ env.AWS_REGION_NAME }}

      - name: Create new ElasticBeanstalk Applicaiton Version
        run : |
         aws elasticbeanstalk create-application-version \
         --application-name ${{ env.EB_APPLICATION_NAME }} \
         --source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
         --version-label "Ver-${{ github.sha }}" \
         --description "CommitSHA-${{ github.sha }}"
      - name: Deploy our new Application Version
        run : aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVIRONMENT_NAME }} --version-label "Ver-${{ github.sha }}"

      - name: Print nice message on completion of CD Pipeline
        run : echo "CD Pipeline part finished successfully"  
